version: 2.1
jobs:
  deploy-service:
      docker:
        - image: circleci/node:10.16
        
      parameters:
        service_path:
          type: string
        stage_name:
          type: string

      steps:
        - checkout

        # Download and cache dependencies
        - restore_cache:
            keys:
              - dependencies-cache-{{ checksum "package.json" }}
              # fallback to using the latest cache if no exact match is found
              - dependencies-cache

        - run:
            name: Install Serverless CLI and dependencies
            command: |
              sudo npm i -g serverless
              npm install

        # - run:
        #     name: Run linting
        #     command: npm run lint

        # - run:
        #     name: Run tests with code coverage
        #     command: npm run test:cov

        - run:
            name: Deploy application
            command: |
              cd << parameters.service_path >>
              sls deploy -s << parameters.stage_name >>

        - save_cache:
            paths:
              - node_modules
            key: dependencies-cache-{{ checksum "package.json" }}

workflows:
  version: 2.1
  build-deploy:
    jobs:
      - deploy-service:
          name: Deploy Device API to development
          service_path: services/devices
          stage_name: dev
          context: Development
          filters:
            branches:
              only: dev
      
      - deploy-service:
          name: Deploy Dashboard API to development
          service_path: services/dashboards
          stage_name: dev
          context: Development
          filters:
            branches:
              only: dev

      - deploy-service:
          name: Deploy Scenario API to development
          service_path: services/scenarios
          stage_name: dev
          context: Development
          filters:
            branches:
              only: dev              

      - deploy-service:
          name: Deploy Device API to production
          service_path: services/devices
          stage_name: api
          context: Production
          filters:
            branches:
              only: master
      
      - deploy-service:
          name: Deploy Dashboard API to production
          service_path: services/dashboards
          stage_name: api
          context: Production
          filters:
            branches:
              only: master
      
      - deploy-service:
          name: Deploy Scenario API to production
          service_path: services/scenarios
          stage_name: api
          context: Production
          filters:
            branches:
              only: master