version: '3.9'

services:
  # node:
  #   build: .
  #   ports: 
  #     - "5000:5000"
  #   restart: on-failure
  #   environment:
  #     CONNECTION_STRING: mongodb://mongodb:27017/hotel-booking
  #     PORT: 5000
  #     SECRET: MySecretString
  #     NODE_ENV: development # Used to seeding the database
  #   networks:
  #     - application
  mongodb:
    image: mongo:4.4.4-bionic
    restart: on-failure
    ports:
        - "27018:27017"
    # environment:
    volumes:
      - './mongodb/data:/data/db'
    networks:
      - application

networks:
  application:
    name: application

